14/11/2024

diff --git a/Dockerfile.actions b/Dockerfile.actions
--- a/Dockerfile.actions
+++ b/Dockerfile.actions
@@ -1,8 +1,8 @@
 FROM python:3.9-slim
 FROM rasa/rasa:3.6.2
 
-# Cambiar al usuario root para instalar dependencias
-USER root
+# # Cambiar al usuario root para instalar dependencias
+# USER root
 
 # Configura variables de entorno para reducir el uso de memoria
 ENV PYTHONUNBUFFERED=1
@@ -11,11 +11,11 @@ ENV PORT=5055
 # Configura el directorio de trabajo
 WORKDIR /app
 
-# Instala solo las dependencias esenciales
-RUN apt-get update && apt-get install -y --no-install-recommends \
-    build-essential \
-    python3-dev \
-    && rm -rf /var/lib/apt/lists/*
+# # Instala solo las dependencias esenciales
+# RUN apt-get update && apt-get install -y --no-install-recommends \
+#     build-essential \
+#     python3-dev \
+#     && rm -rf /var/lib/apt/lists/*
 
 # Copia los archivos necesarios
 COPY requirements.txt /app/
@@ -23,13 +23,13 @@ COPY actions ./actions
 
 
 # Instala las dependencias
-RUN pip install --no-cache-dir -r requirements.txt 
+#RUN pip install --no-cache-dir -r requirements.txt 
 
 # Copia el resto de los archivos
 COPY . .
 
-# Cambiar de vuelta al usuario no privilegiado
-USER 1001
+# # Cambiar de vuelta al usuario no privilegiado
+# USER 1001
 
 # Limpia archivos innecesarios
 # RUN apt-get purge -y --auto-remove build-essential python3-dev \
@@ -37,8 +37,8 @@ USER 1001
 #     && find . -type d -name "__pycache__" -exec rm -r {} + \
 #     && rm -rf /root/.cache /tmp/* /var/tmp/*
 
-HEALTHCHECK --interval=60s --timeout=60s --start-period=60s --retries=5 \
-    CMD curl -f http://localhost:$PORT/health || exit 1
+# HEALTHCHECK --interval=60s --timeout=60s --start-period=60s --retries=5 \
+#     CMD curl -f http://localhost:$PORT/health || exit 1
 
 
 # Expone el puerto
